[toolchain]

[features]
seeds = false
skip-lint = false

[provider]
cluster = "https://kathlin-5yytwf-fast-devnet.helius-rpc.com"
wallet = "/Users/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-nft = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNFT.ts"
test-ido = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/ido.ts"
test-vesting = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/vesting.ts"

