[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
kyupad_smart_contract = "3LJYEwPqJ5Lk5B9GXYsmadymm7p6hhCKzBeSMBGXJa9L"

[registry]
url = "https://devnet.helius-rpc.com/?api-key=7b857a49-a695-4d15-8b64-869d6fa1134e"

[provider]
cluster = "Devnet"
wallet = ".config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
