[toolchain]

[features]
seeds = false
skip-lint = false

[provider]
cluster = "localnet"
wallet = ".config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-nft = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mintNFT.ts"
test-ido = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/ido.ts"
