[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
kyupad_smart_contract = "FHPbXuECjkYGrJHnwU2ozrm7TYzoo2c43CZTo3nJEzs"

[registry]
url = "https://kathlin-5yytwf-fast-devnet.helius-rpc.com"

[provider]
cluster = "Devnet"
wallet = "/Users/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
