[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
kyupad_smart_contract = "FHPbXuECjkYGrJHnwU2ozrm7TYzoo2c43CZTo3nJEzs"

[programs.mainnet]
kyupad_smart_contract = "FHPbXuECjkYGrJHnwU2ozrm7TYzoo2c43CZTo3nJEzs"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "mainnet"
wallet = "/Users/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
