[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
kyupad_smart_contract = "7xxCydutAXo4eicZXAN3JZmFCGg2dLqesGkrd8jAobxZ"

[programs.mainnet]
kyupad_smart_contract = "7xxCydutAXo4eicZXAN3JZmFCGg2dLqesGkrd8jAobxZ"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "https://kathlin-5yytwf-fast-devnet.helius-rpc.com"
wallet = "/Users/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
