[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
kyupad_smart_contract = "6CEvPSYN2YpLT4nJd1DFJRQDXkVgsBqq5Bt8bGhkuXWr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
