[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mint_nft_solana = "6MDBAfNk1J7e1mWnsQwgTRffTuusUUpgbCKSiNBPwSYR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
