[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mint_nft_metaplex = "EEXjKscUeFpFsFoK5k2EMV2VTJdn6iiX3CGYFXo9AT8D"

[registry]
url = "https://api.testnet.solana.com"

[provider]
cluster = "testnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
